### ISSUE TITLE
[update] KO

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/garradin_ynh#10]
hi all, 
i just tried to update garradin, and there is an error : 
```
2019-01-29 16:32:35,449: WARNING - Corrupt source
2019-01-29 16:32:35,450: DEBUG - + echo 'c3ba4f83aba2579968080757942bb7aa6b54a603c3b162a2cb4ccdbc8ca5c81b app.tar.bz2'
2019-01-29 16:32:35,450: WARNING - !!
2019-01-29 16:32:35,450: DEBUG - + sha256sum -c --status
2019-01-29 16:32:35,450: WARNING -   garradin's script has encountered an error. Its execution was cancelled.
2019-01-29 16:32:35,450: DEBUG - + ynh_die 'Corrupt source'
2019-01-29 16:32:35,451: WARNING - !!
2019-01-29 16:32:35,451: DEBUG - + echo 'Corrupt source'
2019-01-29 16:32:35,451: WARNING - Upgrade failed.
2019-01-29 16:32:35,451: DEBUG - + exit 1
```
thx for your work && your help ;)

complete log : https://paste.yunohost.org/raw/yanirecola

```
# yunohost -v
yunohost: 
  repo: stable
  version: 3.3.4
yunohost-admin: 
  repo: stable
  version: 3.3.1
moulinette: 
  repo: stable
  version: 3.3.1
ssowat: 
  repo: stable
  version: 3.3.2
```

**Comment by frju365** [comment]
:/ Ok. It's a problem from upstream :/ The package a version on day, but the day after they add or change files and recompress the archive with the same name... :/ so sha256 sum changes. 
Another problem is that, when they release a version, they remove every old version, that is to say that I have to update version in package immediately.

So, I have to speak with dev to find a solution or a compromise quickly, because my package is not maintainable like that. I'm sorry (if we don't find a solution, I will have to package myself :) or do a mirror of garradin repo -- don't worry it doesn't change anything for you)

**Comment by frju365** [comment]
En attendant j'ai encore changé les sha256 (pour la 4e fois en deux jours :/)

**Comment by frju365** [comment]
Well, I keep it opened as I want to have a long-term solution. :-)

**Comment by bohwaz** [comment]
Hi, I never got an email from you as far as I know? But someone mentioned it to me. As you noticed, the package is regenerated when an issue is reported with the packaging (like a missing file or something else). This package is meant for manual installation only, you should not use it for automated installations.

The right way would be to use the dynamic package feature of Fossil, eg. https://fossil.kd2.org/garradin/zip/Garradin.zip?uuid=0.9.2

will get you the latest 0.9.2 release. This package hash can also change, as corrective commits may be applied.

You can use the manifest file to check for file-by-file integrity: https://fossil.kd2.org/garradin/artifact/0.9.2

After that just run "make deps" to download and install the dependencies.

Please contact me if that doesn't suit your workflow so that we can work together to find something that can suit Yunohost :)

Cheers!
