### ISSUE TITLE
Upgrade pass but then redirects to install.php page

### ISSUE THREAD

**Issue by BenoitCier** [YunoHost-Apps/garradin_ynh#65]
Hello, 

  current_version: 1.0.7 ~ ynh2
  id: garradin__2
  label: Garradin
  new_version: 1.1.10 ~ ynh1

the upgrade pass but after upgrade the admin page redirect to the install.php page.
I'm not sure it's the same issue as the other opened

**Comment by alexAubin** [comment]
Another user is reporting the same issue today ...

I don't know much about this app, but it naively seems related to : https://github.com/YunoHost-Apps/garradin_ynh/blob/master/scripts/upgrade#L204

Basically the app overwrites any previous `config.local.php` file ... If this file corresponds to where the app install parameters are stored then it probably means that we're just dropping any previous configuration ...

(Note that this piece of code is also present in the `if [ "$upgrade_type" == "0.9.8" ]` earlier)

The proper way to proceed (assuming this is indeed the root cause of the issue) should be to add `--keep="config.local.php"` to `ynh_setup_source` during the upgrad and to not do any `cp` that would overwrite the config file ..

**Comment by rodinux** [comment]
I can try do this, I haven't seen before this option to keep the file with the new source app. But nevertheless, I am not sure it is the solution... This app is in constant evolution since the versions 1.*. I have one on production where I have upgraded without problems, but from other versions... I think perhaps it need also a pre-upgrade from 1.0.7 to 1.1 before, as we have to do a pre-upgrade from 0.9.8.1 before upgrade to 1.0.*

**Comment by rodinux** [comment]
Ok, I try fixed this issue, working in the branch 1.1.1, you con see this here https://github.com/YunoHost-Apps/garradin_ynh/blob/ea4434f251465d48673fef59a26eadf93d41cd78/scripts/upgrade
Need now testing it

**Comment by rodinux** [comment]
I have a branch 1.0.7 to try fix this issue, I have try to fix it on the branch 1.1, but it fails, O have reproduced the same error installing first the 1.0.7, then backup data (a squlite file from april so from the version 1.0.6) after I try update to the branch 1.1 with my fix but it is the same issue, I come back to the install.php page !

**Comment by rodinux** [comment]
Je ne comprends pas pourquoi je suis arrivé à installer 2 fois Garradin version 1.0.6 pour tester l'upgrade sur un de mes serveurs, puis désinstallés quand ça ne marchait pas. Mais maintenant je n'y arrive plus correctement, après une installation, lors de la post-installation je me retrouve avec cette erreur: 
PHP error
Notice: Undefined property: stdClass::$id_categorie
in .../www/admin/index.php:8
```
4
5require_once __DIR__ . '/_inc.php';
6
7$cats = new Membres\Categories;
8$categorie = $cats->get($user->id_categorie);
9
10$tpl->assign('categorie', $categorie);
11
12$wiki = new Wiki;
```

**Comment by rodinux** [comment]
Ok, I found the solution and tested it, in the branch 1.1, here is the script upgrade with thz fix: https://github.com/YunoHost-Apps/garradin_ynh/pull/63/commits/e6473d4c7cc4c527eb7eea2e1143caaa5687a3d8
There is a PR to push the changes on master branch, I need a reviewer !

**Comment by rodinux** [comment]
> Another user is reporting the same issue today ...
> 
> I don't know much about this app, but it naively seems related to : https://github.com/YunoHost-Apps/garradin_ynh/blob/master/scripts/upgrade#L204
> 
> Basically the app overwrites any previous `config.local.php` file ... If this file corresponds to where the app install parameters are stored then it probably means that we're just dropping any previous configuration ...
> 
> (Note that this piece of code is also present in the `if [ "$upgrade_type" == "0.9.8" ]` earlier)
> 
> The proper way to proceed (assuming this is indeed the root cause of the issue) should be to add `--keep="config.local.php"` to `ynh_setup_source` during the upgrad and to not do any `cp` that would overwrite the config file ..

Done also, and add a condition which resolve a pre-upgrade to 1.1.0 because was also necessary.

**Comment by rodinux** [comment]
Hello, I think this time the script upgrade is working and resolve this issue, waiting for a reviewer to push the PR...

**Comment by rodinux** [comment]
I think this issue could be closed...

**Comment by BenoitCier** [comment]
I agree, i close it, but i have found an other issue
